### PR TITLE
Add Master Tetraminx as `mtetram`.

### PR DESCRIPTION
**Pull request by lgarron**
I've been using this at https://scramble.cubing.net/?event=master_tetraminx already.
https://alpha.twizzle.net/edit/?puzzle=master_tetraminx has also
supported master tetra for for quite a while (but not master pyra), as
I'd like to advocate for leaving out tips on the larger variants.

Screen Shot 2022-01-31 at 15 50 50

I would prefer to use `master_tetraminx`, but `mtetram` matches existing events more closely.

### CODE REVIEW

**Comment by lgarron** [comment]
Another option would be to explicitly chop off the tips, more similar to the traditional Tetraminx puzzle:
Screen Shot 2022-01-31 at 04 35 33

Or a more of an intermediate:
Screen Shot 2022-01-31 at 04 41 22

**Review by jfly — APPROVED** [review]
LGTM! No opinions here on the tips.

**Comment by lgarron** [comment]
> Screen Shot 2022-01-31 at 04 46 46 1

I'm actually really warming up to this one. 

It's occurred to me that we do have `mpyram` in the icon set already. Alright with switching to this one?

**Comment by jfly** [comment]
Let's stick with the old name? I still don't feel strongly about the actual icon.

**Comment by lgarron** [comment]
> Let's stick with the old name? I still don't feel strongly about the actual icon.

How so? I'm keeping `mpyram`, just adding `mtetram` (as in the original version of this PR).

**Comment by jfly** [comment]
Oh got it! Sorry, I like the plan.

**Comment by keemy** [comment]
i kinda like the more cut off tips or blocky one more
image
 but tbh any seem fine

**Pull request merged**
