### PR TITLE
added very basic magic and master magic svg

### PR DESCRIPTION
**Pull request by keemy**
#8

### CODE REVIEW

**Comment by jfly** [comment]
Could you add screenshots?

**Comment by keemy** [comment]
can see them https://github.com/cubing/icons/blob/8039fb84d1ca42665b03af9ed3032fdbab55af1a/svgs/event/magic.svg
https://github.com/cubing/icons/blob/8039fb84d1ca42665b03af9ed3032fdbab55af1a/svgs/event/mmagic.svg

but here are screenshots

image

image

**Comment by lgarron** [comment]
The basic magic image looks a a lot like 3x3x3. Don't have any great alternative suggestions, though.

**Comment by jonatanklosko** [comment]
I can imagine this without any space, just a single shape. This wouldn't resemble 3x3 anymore =)

**Comment by keemy** [comment]
Yeah I had a few ideas but none was looking very good (also I no longer have illustrator) so feel free to change. Also if you think of something for old mblind would be good too.

**Pull request merged**
