### PR TITLE
Change Travis to run on latest stable `node`.

### PR DESCRIPTION
**Pull request by lgarron**
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Specifying-Node.js-versions

### CODE REVIEW

**Comment by jfly** [comment]
Thanks, @lgarron. This looks fine to me (glad to see that Node LTS is still passing). My only concern is that when we deploy to master, I think we'll have two simultaneous Travis jobs that are racing to deploy to gh-pages, and I guess we'll end up with 2 commits to our gh-pages branch, once with whatever "node" corresponds to, and one with whatever "lts" corresponds to. That feels a bit funky to me, although it will probably be fine... what do you think?

**Comment by lgarron** [comment]
oic; they both create commits? Then how about just sticking with latest

**Comment by jfly** [comment]
> they both create commits?

I think so. What I think will happen:

1. They both execute `npm run deploy`: https://github.com/cubing/icons/blob/9879ddfd5a17bc6fd976e91e4764626b3bd6b187/.travis.yml#L12.
2. They both end up pushing to gh-pages: https://github.com/cubing/icons/blob/9879ddfd5a17bc6fd976e91e4764626b3bd6b187/gulpfile.babel.js#L91-L96.

> Then how about just sticking with latest?

Sorry, are you referring to latest node version here? Or something else?

**Comment by lgarron** [comment]
> Sorry, are you referring to latest node version here? Or something else?

Yeah, that's the `- "node"` line.

**Comment by jfly** [comment]
Sure, that sounds good to me!

**Pull request merged**
