### PR TITLE
Add Icon for Face Turning Octahedron

### PR DESCRIPTION
**Pull request by saranshgrover**
Not sure if I need to do something besides add the svg. Let me know if there's anything else.

### CODE REVIEW

**Comment by lgarron** [comment]
*woo*, I'm glad to see this! :-D

To thoughts:
1) Right now, this looks a lot like a grid of triangles rather than a corner view of an octahedron. What about separating the four faces a bit to emphasize that the overall geometry?

Screen Shot 2020-06-04 at 21 12 40

2) How does this look at a smaller scale? Is it possible to simplify this a bit more without making it too difficult to add for future puzzles, like we did for clock?

**Comment by saranshgrover** [comment]
Hmm - I agree that it may be too complicated for smaller views. I like the second image, the last one seems too simple imo. I can update the svg with the 2nd image if that sounds good to you.

**Comment by lgarron** [comment]
I've sent a PR for the spaced version with the right dimensions at https://github.com/cubing/icons/pull/64

I think the simplified ones could cause issues for us in the future, since they are more appropriate for representing other puzzles.

**Comment by lgarron** [comment]
Landed in #64; thanks for getting this rolling!

**Pull request closed without merging**
