### PR TITLE
unofficial-BLD

### PR DESCRIPTION
**Pull request by MikeHughey1**
Attempting to add 6x6x6 and 7x7x7 BLD icons.

### CODE REVIEW

**Comment by FatBoyXPC** [comment]
I see no issue with adding unofficial icons! Anybody else? @keemy or @jfly?

Would you be willing to also rebuild the fonts and include them as part of this PR? I think you're on windows and I don't know how difficult it would be to rebuild them on windows.

**Comment by MikeHughey1** [comment]
Sorry - I've been communicating with jfly by email about this.

The reason I did this pull request was precisely because I'm having trouble building the icons on Windows and I can't figure out why.

**Comment by FatBoyXPC** [comment]
Alright, I'll see if I can't pull this branch and hook it up in a little bit :)

**Comment by jfly** [comment]
> Would you be willing to also rebuild the fonts and include them as part of this PR?

Doesn't Travis handle that for us? We shouldn't be committing compiled assets.

**Comment by FatBoyXPC** [comment]
D'oh! I didn't realize that the fonts were last committed 3 years ago! I figured there would be a way to have Travis do the build for us, but when I read the gulp file the first time I only looked at `TravisHelper` rather than `deployTravis`. Okay, yeah, @MikeHughey1 I don't think you need to worry about getting the build going!

**Comment by keemy** [comment]
seems good to me

**Pull request merged**
