### PR TITLE
Adding numbers into the big cube icons.

### PR DESCRIPTION
**Pull request by jfly**
(See discussion over on #13.)

You can see this live on http://www.jflei.com/icons/

jsfiddle: https://jsfiddle.net/cgb1Luvu/2/

### CODE REVIEW

**Comment by keemy** [comment]
my vote is no 
```
the only icon that looks ok is the 5
but I think changing 4 and 5 is pointless (no added clarity imo)
and the 6 and 7 look bad

I'd want to change 6 and 7 if it looked good
I really don't want to change 4 and 5
```

**Comment by jfly** [comment]
(cc-ing @FatBoyXPC, @lgarron)

**Comment by coder13** [comment]
I don't really like the 6 and 7 being off center. I'd much rather than me centered if that.

Also: maybe just bold the centers for the odd cubes (5 and 7). 4 and 6 are pretty distinguishable and so are 5 and 7. All you need to do is tell 6 and 7 apart by bolding the center.

**Comment by lgarron** [comment]
Didn't we settle on different ones further down the thread?

**Comment by AlexMaass** [comment]
@lgarron you mean these right? https://github.com/cubing/icons/issues/13#issuecomment-272029816
I personally like those better, what do you guys think?

**Comment by jfly** [comment]
> @lgarron you mean these right? https://github.com/cubing/icons/issues/13#issuecomment-272029816

Those are both in my first commit. See https://github.com/jfly/icons/tree/e98a7851ba5f3a930e5578adcf40ffd7dca1554b/svgs/event.

@keemy and I both do not like the unabalanced nature of the 6 here: https://github.com/jfly/icons/blob/e98a7851ba5f3a930e5578adcf40ffd7dca1554b/svgs/event/666.svg. Going only 5 pixels tall allows us to achieve a balanced look.

@keemy and I both do not like the blocky nature of the slanted 7 here: https://github.com/jfly/icons/blob/e98a7851ba5f3a930e5578adcf40ffd7dca1554b/svgs/event/777.svg, so we went with the straight lines.

I really like the sound of @coder13's idea to just make the centers stand out. That might look good. I'm going to try that out now.

**Comment by lgarron** [comment]
> @keemy and I both do not like the unabalanced nature of the 6 here: https://github.com/jfly/icons/blob/e98a7851ba5f3a930e5578adcf40ffd7dca1554b/svgs/event/666.svg. Going only 5 pixels tall allows us to achieve a balanced look.

Okay, good to know. No one at #13 commented on that, though?

I have no objections to making #6 shorter, but we should be consistent about whether to center.

> @keemy and I both do not like the blocky nature of the slanted 7 here: https://github.com/jfly/icons/blob/e98a7851ba5f3a930e5578adcf40ffd7dca1554b/svgs/event/777.svg, so we went with the straight lines.

What about all the other `7` designs in the thread?
(I just posted a thicker one, since the cubies are about half the size of 4x4x4, anyhow.)

**Comment by keemy** [comment]
>Okay, good to know. No one at #13 commented on that, though?

was literally my first comment "the top of the 6 is bigger than the bottom"

**Comment by lgarron** [comment]
> was literally my first comment "the top of the 6 is bigger than the bottom"

Ah, that was before I joined the thread.

What about making the 6 shorter, but still centered?

**Comment by jfly** [comment]
There didn't seem to be an consensus on this, so I'm going to close this PR.

**Pull request closed without merging**
