### PR TITLE
Add 3x3 + OH + BLD Relay and Team Factory icons

### PR DESCRIPTION
**Pull request by dmint789**
This PR makes the following changes:

Add 3x3 + OH + BLD Relay icon (`333-oh-bld-relay`)
Add 3x3 + OH + BLD Team Relay icon (`333-oh-bld-team-relay`)
Add 3x3 Team Factory icon (`333-team-factory`). Similar idea to the Team-Blind icon.
Slightly tweak Team-Blind icon, making the circles a little smaller. The circles are consistent between Team Factory and Team Blind.

Previews:

Untitled

This solves part of #105

### CODE REVIEW

**Comment by dmint789** [comment]
I figured it made more sense to include the non-team version of 3x3 + OH + BLD relay icon too, since that's the less specific case, and then the team version simply builds on that icon, using the exact same 3 circles as in 3x3 BLD 3-man relay.

**Review by jfly — COMMENTED** [review]
Team factory and team bld look good to me.

The relay icons look quite crowded to me, but I don't actually have a suggestion for fixing them.

Approved from my perspective, but I'd like to hear from another maintainer (@lgarron?) before merging.

**Comment by dmint789** [comment]
I just went with the same idea as Mini guildford. I actually think it looks alright, because it's quite clear what it represents.

**Comment by dmint789** [comment]
One option is to replace the OH cube with a single square, same as Mini Guildford does it

**Comment by dmint789** [comment]
@jfly I have made the aforementioned change, now it's the same as in Mini Guildford:

333-oh-bld-relay

**Comment by dmint789** [comment]
I would appreciate having a new NPM package version once this PR is merged. I would like to use all of the new icons.

**Comment by jfly** [comment]
I'll merge this (and do an npm release) early next week unless another maintainer gives feedback before then.

**Comment by dmint789** [comment]
@jfly Could you deploy this today? I would like to add the new icons to my website :)

**Comment by jfly** [comment]
I'll merge this tomorrow morning unless someone chimes in before then. @lgarron last change for feedback! (of course, we can always change these things in the future if want)

**Review by lgarron — APPROVED** [review]
I'd love to find a better way to combine separate icons (maybe a [cartouche](https://en.wikipedia.org/wiki/Cartouche)?) at some point, but these look good to me for now!

**Comment by jfly** [comment]
@dmint789 version 1.0.9 (https://github.com/cubing/icons/releases/tag/v1.0.9) of @cubing/icons has been released to npm.

**Comment by dmint789** [comment]
@jfly thank you! I've already updated my package :)

**Comment by lgarron** [comment]
Did we not want to use underscores before releasing?

**Comment by dmint789** [comment]
@jfly this character: _
@lgarron well, we ended up sticking with dashes in both this PR and the Team-Blind one, to stick with the convention started by mirror cube.

**Comment by jfly** [comment]
Ahh sorry, I thought we were talking about release naming conventions or something.

Let's continue the discussion about naming conventions over on https://github.com/cubing/icons/issues/108

**Pull request merged**
