### PR TITLE
Move vertical-align so it applies to regular sized icons as well.

### PR DESCRIPTION
**Pull request by jfly**
Before (http://cubing.github.io/icons/):

image

After (https://www.jflei.com/icons/):

image

### CODE REVIEW

**Comment by keemy** [comment]
SeemsGood

**Comment by Baiqiang** [comment]
Tested it out just now. They don't align middle in larger size.
https://jsfiddle.net/cgb1Luvu/10/

**Comment by Baiqiang** [comment]
I think we should add different vertical-align for different sizes.

**Comment by jfly** [comment]
I've added a `vertical-align: middle;` to `.cubing-icon`, which seems to help! Your JSFiddle seems to be working nicely as well: +  vertical-align: middle;
. Let me know what you think!

**Comment by Baiqiang** [comment]
I thinks you should remove the `vertical-align: -15%`, or the icons look a bit upper.
image

**Comment by jfly** [comment]
Oh, that's strange. For me, with the `vertical-align: -15%`:

image

For me, without the `vertical-align: -15%`:

image

This might be related to the chinese characters in your example. Could you provide a jsfiddle?

**Comment by Baiqiang** [comment]
For me, with `vertical-align: -15%`:
image
Without: 
image

I don't think it's something related to the Chinese. My browser is Chrome 56.0.2924.87 on windows 10.

**Comment by Baiqiang** [comment]
Just testes with more browsers. It seems only my chrome on windows behaves strange. I've no idea on this.

**Pull request merged**
