### PR TITLE
Add `fto`.

### PR DESCRIPTION
**Pull request by lgarron**
This uses a common orientation for the puzzle and separate faces, per https://github.com/cubing/icons/pull/49

### CODE REVIEW

**Comment by lgarron** [comment]
@saranshgrover, @jfly: This is a version of https://github.com/cubing/icons/pull/49#issuecomment-639247677 with dimensions exactly sized to match the other icons (500x500, with 30px padding).

Does it look good too you?

**Comment by lgarron** [comment]
It stays moderately recognizable at different resolutiions:
fto
Screen Shot 2021-03-25 at 02 00 33
Screen Shot 2021-03-25 at 02 00 49

**Comment by keemy** [comment]
this seems fine.

**Comment by jfly** [comment]
LGTM!

**Pull request merged**
