### PR TITLE
Add Linear FMC icon

### PR DESCRIPTION
**Pull request by dmint789**
This is a new event @lgarron started organizing and we will be holding it at Euros this year. The idea is that you just do one attempt at solving a 3x3 with as few moves as possible, and you can't backtrack (hence the arrow). Output image:

333_linear_fm

### CODE REVIEW

**Comment by dmint789** [comment]
@jfly if this could be included in a new npm release along with the updated mirror bld icon, that would be great for us!

**Review by jfly — APPROVED** [review]
LGTM!

**Comment by jfly** [comment]
@dmint789, [v1.1.3](https://www.npmjs.com/package/@cubing/icons/v/1.1.3) is out now.

**Comment by dmint789** [comment]
@jfly thank you!

**Pull request merged**
