### PR TITLE
Add 2/3/4/8-man 3x3 Blindfolded relay icons

### PR DESCRIPTION
**Pull request by dmint789**
This fulfills part of #105. Preview:

333bf

### CODE REVIEW

**Review by jfly — COMMENTED** [review]
The icons seems reasonable to me, but let's come up with less cryptic names for these icons.

**Comment by dmint789** [comment]
@jfly how about 333bf-Nman-relay, where N is the number of people

**Comment by jfly** [comment]
> how about 333bf-Nman-relay, where N is the number of people

I like this, although we should avoid dashes, as those are our folder delimiter in this repo.

@lgarron, thoughts? Sure would be nice to have a better word than "man". "cuber"? "person"?

**Comment by dmint789** [comment]
@jfly But mirror blocks uses dashes

**Comment by jfly** [comment]
> although we should avoid dashes, as those are our folder delimiter in this repo

Nevermind, you reminded me [here](https://github.com/cubing/icons/pull/106#issuecomment-1712192607) that we're already using kebab case. Let's stay consistent!

**Comment by lgarron** [comment]
> > although we should avoid dashes, as those are our folder delimiter in this repo
> 
> Nevermind, you reminded me [here](https://github.com/cubing/icons/pull/106#issuecomment-1712192607) that we're already using kebab case. Let's stay consistent!

That was mostly to match existing CSS names.

I would be more favor of underscores if we're okay with mixed hyphens and underscores in CSS. (I'm probably the only one using the mirror blocks icon, so renaming it is not a big concern).

**Comment by dmint789** [comment]
I would prefer to either have everything in snake_case or everything in kebab-case, so if renaming mirror works, then we can go with that. We can just keep a duplicate with kebab-case so as not to break other people's stuff.

**Comment by lgarron** [comment]
> @lgarron, thoughts? Sure would be nice to have a better word than "man". "cuber"? "person"?

Definitely in favor of "person"! That's also what the WCA website uses.

I'd go with `333_bld_N_person_relay`.

**Comment by dmint789** [comment]
That is so long, can we not think of something more elegant? How about 333bf_Np_relay? I strongly believe we should keep 333bf in the front, since it's just an extension of the 3x3 Blindfolded event.

**Comment by lgarron** [comment]
I'm fine with `333bf` as a prefix to keep some consistency with the existing event, but I definitely don't consider short names elegant. I think it's much more valuable for the name to make sense without context, and I struggle to think of a situation where `333bf_N_person_relay` would fundamentally cause issues.

**Comment by dmint789** [comment]
Okay, I agree. Although seeing as we now have two icons with kebab-case it seems like it would make more sense to use that here too.

**Comment by lgarron** [comment]
Also, just checking: do all four of these events correspond to relays that people actually do?

I am generally in favor of erring on the side of too many icons, but it could be wise to encourage a slimmer set of choices to start.

**Comment by dmint789** [comment]
> Also, just checking: do all four of these events correspond to relays that people actually do?
> 
> I am generally in favor of erring on the side of too many icons, but it could be wise to encourage a slimmer set of choices to start.

These are all popular categories. There is also 5-man and 10-man, but I have seen very few of those. Feel free to have a look at the [cubingcontests.com rankings](https://cubingcontests.com/rankings/333bf2mr/single) for these events. And that is just what I've found so far.

**Comment by dmint789** [comment]
@jfly I think this is all done too now

**Review by jfly — APPROVED** [review]

**Comment by jfly** [comment]
Thanks!

**Comment by dmint789** [comment]
Yay, now I can use more icons! I will work on team factory and 3x3 oh bld team relay icons tomorrow, I suppose.

**Comment by dmint789** [comment]
@jfly how long does it take until a new version is rolled out, and how does that process work?

**Comment by jfly** [comment]
I can do a release if that helps you. We don't really have a process around this.

**Comment by dmint789** [comment]
I see. Let's do it after I add the other two icons, so I'm not bothering you over and over again.

**Pull request merged**
