### PR TITLE
Created 3x3x3 Mirror Icon

### PR DESCRIPTION
**Pull request by sushantshah-dev**
Update to https://github.com/cubing/icons/pull/98

### CODE REVIEW

**Review by lgarron — APPROVED** [review]
I think this looks pretty good!

Notwithstanding https://github.com/cubing/icons/pull/98#pullrequestreview-1542159171 , I think `333-mirror-blocks` is reasonable balance of currently common name vs. future-proof.

**Comment by lgarron** [comment]
@jfly: good with this?

**Review by jfly — APPROVED** [review]
LGTM!

**Comment by sushantshah-dev** [comment]
What about adding it to the fonts?

**Comment by jfly** [comment]
@sushantshah-dev the font includes all `svgs/*/*.svg` files. See https://github.com/cubing/icons/blob/a175a894336d16d1c1f0429443ada4cedba290b4/gulpfile.babel.js#L26.

Are you seeing something different?

**Pull request merged**
