### PR TITLE
Additional unofficial events

### PR DESCRIPTION
**Pull request by MikeHughey1**
svgs for additional unofficial events - relays, match the scramble, kilominx, 2x2x2 BLD, mini Guildford

### CODE REVIEW

**Comment by FatBoyXPC** [comment]
The only icon that concerns me is 333mts. I love the design showing that you're going from solved to scramble, but hopefully this font isn't monospaced! Want me to do a build and find out, or shall we yolo it?

**Comment by MikeHughey1** [comment]
Sorry, I'm an idiot - I don't understand.  Why is monospaced an issue?

I know that the particular icon is very flattened; I couldn't think of a
better way for it.  I suppose I could put them at a diagonal if you think
that helps.  But I'm not sure what that really accomplishes - there's still
just as much unexplained space that way, but I guess it's at a diagonal
then, so you can see how big it's really supposed to be.

**Comment by MikeHughey1** [comment]
But I guess yeah, please build it.  I'd like to have it this way anyway, in
case fixing things takes a while.

**Comment by FatBoyXPC** [comment]
Monospace would make it so that every font character is the same width, which in this case, would make 333mts be super tiny compared to the rest. I'll build it and send it!

**Comment by MikeHughey1** [comment]
Well, not really.  The cubes in 333mts are still a good bit bigger than the
ones in the relays, even in monospacing.

**Comment by MikeHughey1** [comment]
And anyway, I would think a point of these is that they should be treated
as the same size - that way they work well as, say, menu items, like what
we do on the WCA person results webpage.  I know mts doesn't look that
great, but given those constraints, I don't see a good alternative.

**Comment by FatBoyXPC** [comment]
Yeah, I don't see a great alternative, either. I just checked and the canvas area is the same size, so I think this is actually just safe to merge. Any objection?

**Comment by MikeHughey1** [comment]
I'm not really in a hurry to merge it, although I would like a built
version as soon as I can get it.  I'm happy to make any changes anyone
might suggest before we do merge it.  Or if you'd rather we can merge it
now and just make further changes as later pull requests.

**Comment by FatBoyXPC** [comment]
I was talking to @jfly and he said let's just yolo it, so I'm merging it :)

**Comment by MikeHughey1** [comment]
Well, cool - thank you!

**Comment by MikeHughey1** [comment]
I would like to say: thank you!  They look really nice on the
speedsolving.com competition website!

One thing I am noticing now that I see them as large icons on my page is
that kilominx has too much space between the pieces compared to all the
others.  I'll try to eventually clean that up.

**Comment by keemy** [comment]
@FatBoyXPC bruh with this many icons we could at least wait a day so everyone has a chance to look at them and make suggestions or changes...

**Comment by FatBoyXPC** [comment]
See message where I said I talked with @jfly about it =)

**Comment by keemy** [comment]
I really don't like almost any of these and the ones that are ok have white spacing inconsistent with the normal set of icons..

**Comment by FatBoyXPC** [comment]
So reply with some specifics and let @MikeHughey1 change it =)

**Pull request merged**
