### PR TITLE
Added penalty icons originally created by Yaozong Liang (梁耀宗)

### PR DESCRIPTION
**Pull request by jfly**
I opted to create a `svgs/events/` folder and a `svgs/penalties/` folder. Not sure if this is best, or if we should maintain a flattened folder with filename prefixes, or something else entirely. I wanted to create this PR so we could get the discussion going. @keemy @FatBoyXPC, what are your thoughts?

This is relevant to #4.

Note: I have not attempted to generate the new font yet.

### CODE REVIEW

**Comment by FatBoyXPC** [comment]
Moving the icons into appropriate subdirectories seems logical enough to me. I really like the fact that the penalty names are the regulation, however, is there a way to name them something sensible? I understand that the catch here is making it so the filename isn't ridiculously long.

I would like to hold off on merging this until the font is generated. I prefer somebody who hasn't yet generated a font, but contributes to this repo, does so. That way we can make sure the README I wrote some time ago is still (if it ever was) accurate.

Also - I'd like to note that merging this PR will break the docs. Is there a fancy way to create a PR to the gh-pages branch that merges when this merges? @jfly, I know you're a git and GitHub wizard now, so I'm hoping you have an answer to this :D

**Comment by zenkeemy** [comment]
can it be named something like misc because presumably this would go in the same folder as other random icons (like podium, medals, lunch, etc.)

**Comment by FatBoyXPC** [comment]
Hm, I feel like we have enough penalty icons to put them in its own group.

@jfly, how can we tell A4b1 and A6c apart from each other? A6e's image also gives the impression that A6c is being broken, but I think that's more of a problem with this image being 2D.

Shouldn't A3b.svg be A4b.svg? Regulations [A3b](https://www.worldcubeassociation.org/regulations/#A3b) and [A4b](https://www.worldcubeassociation.org/regulations/#A4b) for quick reference.

**Comment by jfly** [comment]
> can it be named something like misc because presumably this would go in the same folder as other random icons (like podium, medals, lunch, etc.)

I do like the idea of having more structure and revisiting this if and when these other things are added.

> I prefer somebody who hasn't yet generated a font, but contributes to this repo, does so.

I can give it a shot once we're happy with the everything else.

> Is there a fancy way to create a PR to the gh-pages branch that merges when this merges?

Ah, not that I know of. I think the "right" answer is to not have the gh-pages branch depend on anything in the master branch. Not saying that's worth the effort, though.

> how can we tell A4b1 and A6c apart from each other (from the perspective of the judge)? Maybe if we put a time or placeholder in the stackmat LCD area?

Ahh, those are the exact same icon right now, aren't they? A4b1 concerns starting the timer without touching the puzzle, and A6c concerns stopping the timer without touching the puzzle?

> A6e and A6c can seem confusing, but I think that's more of a problem with this image being 2D.

Agreed. It would be nice if A6c conveyed a sense of having stopped the timer/solved the puzzle.

A6e doesn't really convey that the timer is stopped, and the competitor is moving to pick up the puzzle before letting the judge inspect the puzzle. It's going to require some serious creativity to convey all that in the confines of a black and white static icon.

> Shouldn't A3b.svg be A4b.svg? Regulations A3b and A4b for quick reference.

Oh, good catch! That mistake came from the files @Baiqiang sent me, and I didn't actually try to think about any of the images, I was just focusing on vectorizing them. Thanks for actually taking a look! I've committed a rename.

> Did Yaozong Liang agree to the icons under the license(s) in this repo?

Ah good point. In the email thread, @Baiqiang said:

> Hi Jeremy,
> You're welcome to add those icons. A Chinese cuber called Yaozong Liang created them instead of me. We provide a score-card template on Cubing China: http://cubingchina.com/static/score-card.xlsx.
If you need other format of those icons, such as psd, I'll contact the designer.

@Baiqiang, do you know if it's okay for us to release these icons under the [MIT license](https://github.com/cubing/icons/blob/master/LICENSE) used by this repository?

**Comment by lgarron** [comment]
Could someone post a screenshot in this thread?

**Comment by jfly** [comment]
> Could someone post a screenshot in this thread?

GitHub is nice enough to render SVGs here <https://github.com/jfly/icons/tree/master/svgs/penalties>

**Comment by Baiqiang** [comment]
@jfly Yaozong only said two letters: OK.

**Comment by lgarron** [comment]
I think the cubes in these icons are way too small. Could we possibly make them 50% larger (in both dimensions)?

**Comment by lgarron** [comment]
A4d2 should be A4d1.

**Comment by jfly** [comment]
Good catch, @lgarron! I've fixed that filename.

I've cleaned up the svgs and made the cubes bigger.

I'm going to give IcoMoon a shot now.

**Comment by jfly** [comment]
Ok, I decided I didn't want to go through with IcoMoon, and opted to create a Gulp based build system in https://github.com/jfly/icons/commit/aed0f38348a0cc04934e946149feaeb9079f340a. It's as easy as running `gulp`, and as easy as running `gulp deploy` to push to the `gh-pages` branch. I now have a `gh-pages` branch on my fork, so you can see the result here http://www.jflei.com/icons/.

Any objections to merging this up?

**Comment by FatBoyXPC** [comment]
LGTM! :shipit:

**Pull request merged**
