### PR TITLE
Revert "Additional unofficial events"

### PR DESCRIPTION
**Pull request by keemy**
Reverts cubing/icons#31

I don't mean to be a dick or something I just wanted to give feedback before like 8 new things got added. 

1. 2BLD and kilo are fine but the whitespace is no consistent with the rest of the icons.
2. I don't think the mts one needs the arrow and stuff just have it be the thing on the right
3. I'm not a fan of all the relays (especially guilford) because you can represent relays by just using all the individual icons that make up the relay, maybe we could add a baton icon to represent relays in general. If they are necessary I think they could look better/more consistent if they used the same way that the bld events represent sizes and just stack them like a pyramid (I dont have illustrator on this computer but the idea would be something like the attached image done properly) 
image

### CODE REVIEW

**Comment by FatBoyXPC** [comment]
Can you give more specific reasons why?

**Comment by keemy** [comment]
typing up reasons now

**Comment by keemy** [comment]
@MikeHughey1

**Comment by MikeHughey1** [comment]
Thanks for the feedback - I'm happy to try to improve these!
#1: I totally agree.  I will work on kilominx - it should be easy enough to get it the same as megaminx and pyraminx.   I'm not sure how to determine the right spacing for 2BLD, though - I had to shrink the squares and I'm not sure what consistent spacing would actually be.  I can just make them a little closer and see if that's good enough, but if you know exactly what the spacing should be (or how to calculate it), I'd be happy to set it to that.
#2: I'm fine with making that change if everyone else agrees.  It seems like your suggestion might be a better overall icon.
#3: I'm not sure I understand what you mean by using all the individual icons: how would we represent a relay (especially Guildford) as a single menu pick, like in the individual Persons Results tab, by combining the icons?  I sort of assumed that if it was a single event, we'd need a single icon for it in order to be able to do those events consistently.  (if we did the pyramid thing, did you mean for them to be sideways like that, or did you intend to stack them, so 90 degrees rotated from what you show there?)

**Comment by jfly** [comment]
@keemy okay merging up this PR immediately and then continuing the discussion of how to improve this icons.

Moving forward, shall we wait for all 3 of the maintainers (@jfly, @FatBoyXPC, and @keemy) to approve a PR that changes or adds icons before merging it up?

**Comment by keemy** [comment]
1. yeah I think for the 2bld it's just if you see the spacing between the squares on the normal 222 icon the ratio is very different from the 2bld icon you made. If you need to scale it down i think that's ok but would pref the same whitespace ratio.

3. Yeah i think this is just like I'm not sure what your menu looks like but it's like having separate icons for every possible relay just looked sort of weird. like for example the 2 -7 relay could look for example like
<baton_icon>: <222>-<777> or
<222>-<777> <baton_icon> or just
<222>-<777> or
<222><333><444><555><666><777>

and guilford could just be like
<baton_icon>: guilford

 for the pyramid I didn't have a particular orientation in mind though most of the other icons read left to right (except oh i guess)

**Comment by MikeHughey1** [comment]
1. Okay, I think I have the 2BLD one figured out then.
2. Okay, I'm going to go ahead and say then that I think we need separate icons for each relay.  At the very least, I'm sure **I** need separate icons for each relay.  I want to be able to set up a personal records page like the WCA one for the speedcubing.com competition website (like this one: https://www.worldcubeassociation.org/persons/2007HUGH01), and I think it would look very inconsistent to try to combine icons for that - they really need to be separate icons.

Since that's the case, I'm going to go ahead and offer some new relay icons doing the pyramid thing.  I will need them for my competition website anyway.  I'm still not sure how to handle Guildford.  Should I just replace the cubes part with the pyramid, but otherwise leave it as is, or are there other suggestions that might work better?  If there are no other suggestions, I'll probably just try to replace the cubes part with the pyramid.  I'm also not sure how else to handle skewb and square-1.  I can try to add lines in them, but I think they'll be too small.

**Pull request merged**
