### PR TITLE
Change the clock icon to a single face.

### PR DESCRIPTION
**Pull request by lgarron**
This makes is a bit simpler, and helps distinguish it from 3x3x3 at a glance, even at low resolutions.

### CODE REVIEW

**Comment by keemy** [comment]
can you add the regenerated fonts files as part of this pull request

**Comment by lgarron** [comment]
Probably. The README doesn't make it clear exactly what steps are needed for that, though.

**Comment by keemy** [comment]
@FatBoyXPC

**Comment by FatBoyXPC** [comment]
I committed early so Jeremy could have the font. I plan on finishing the
read me tonight

**Comment by FatBoyXPC** [comment]
Updated the readme.

@lgarron Go ahead and give updating the fonts a shot. I tried to be as clear as possible in updating the readme.

**Comment by lgarron** [comment]
If I follow the instructions, I end up with a lighter-colored icon for clock. (All the SVGs use grey instead of black.)
Should I edit the SVGs to use black areas before uploading to IcoMoon?

**Comment by FatBoyXPC** [comment]
Just keep the svg the same color that Devin made them. Their default color
will be gray, but the css defaults it to black.

**Comment by FatBoyXPC** [comment]
If you want to edit all the SVGs to be black instead I'd gray, then that
would work as well. I just want all the SVGs to be the same color without
styling.

**Comment by lgarron** [comment]
Fonts added.

**Comment by lgarron** [comment]
@FatBoyXPC: I still can't get the clock icon to show up in demo.html

I presume IcoMoon is treating the clock icon differently, but nothing tells me why/how.

IcoMoon website showing `clock` in gray:
screenshot 2015-02-01 15 33 37


CSS scoped to a particular SVG path:
screenshot 2015-02-01 15 32 00


Clock missing from `demo.html`:
screenshot 2015-02-01 15 31 42


Also, the instructions in `README.md` don't talk about replacing `selection.json`. Should I be doing that?

**Comment by FatBoyXPC** [comment]
The demo shouldn't need changed as it only references CSS classes. Step 14, though, mentions needing to replace selection.json.

About getting the new clock to show up: Have you updated the css, and all the fonts? If yes, have you tried a hard refresh to clear the cache?

**Comment by FatBoyXPC** [comment]
Actually, looking at the CSS, it looks like icon-clock no longer exists, and it's .icon-clock .path1, same with path2 and path3. This means it's looking for an element clased with path1/2/3 inside an element classed with clock. That is why it's not rendering. Any idea what caused this? The CSS is just messed up, is all. It might be worth regenerating the font.

**Comment by Baiqiang** [comment]
The icon clock has been separated into 3 parts because there're two different colors in the svg file. I've tried many changes on the svg file and found on solution to the font, which is changing the colors to the same one. It looks like a whole circle block. But when it's generated, it looks fine. See the following images.

qq 20150202135729
qq 20150202135742

**Comment by FatBoyXPC** [comment]
@Baiqiang Ah yes, I see how it's 2 colors now. The white "clock hand" should be transparent, and that would solve this issue. I actually much prefer that solution, rather than merging things together.

@lgarron Could you make the clock hand transparent instead of white?

**Comment by lgarron** [comment]
Finally got it to work. Anyone willing to give me the okay to merge?

screenshot 2015-02-02 23 08 59

**Comment by jfly** [comment]
LGTM! Thanks for the screenshot. @FatBoyXPC or @keemy, could you merge this?

**Comment by lgarron** [comment]
Also, thanks for the investigation, @Baiqiang. In the end, I decided to flatten all the paths into a single one.
This makes it harder to edit correctly, but I don't anticipate we'll need to do that often.

**Comment by FatBoyXPC** [comment]
@lgarron What do you mean by you decided to flatten all the paths into a single one? Is that something to do with editing SVGs? Thanks for the update, looks so sexy now :D

**Comment by lgarron** [comment]
> @lgarron What do you mean by you decided to flatten all the paths into a single one? Is that something to do with editing SVGs? Thanks for the update, looks so sexy now :D

If you look at the contents of the file, there's now only one path instead of three.
(I took a difference of the outer two shapes and then a union with the middle one.)

**Comment by FatBoyXPC** [comment]
Hm, that's interesting. I assume you mean the <path /> tag in the svg file? I assumed you'd fix this in an image editor. I was actually unable to see the other paths in the old commits (they're gone? Or I suck at history), but this is definitely interesting!

**Comment by lgarron** [comment]
> Hm, that's interesting. I assume you mean the tag in the svg file?

[Yep](https://github.com/cubing/icons/blob/master/svgs/clock.svg?short_path=2d35cdc#L44).

> I assumed you'd fix this in an image editor.

[Yep](https://inkscape.org/en/)!

> I was actually unable to see the other paths in the old commits (they're gone? Or I suck at history), but this is definitely interesting!
I replaced the file in this pull request, because I presume no one would ever need it. But yeah, there were three paths.

**Comment by FatBoyXPC** [comment]
Using Inkscape definitely makes all this make more sense now :D

**Pull request merged**
