### PR TITLE
Add new icons: 2x2x2 OH, Mirror Blocks Blindfolded, 4x4x4 With Feet

### PR DESCRIPTION
**Pull request by dmint789**

### CODE REVIEW

**Review by jfly — APPROVED** [review]
The icons LGTM! But @lgarron might have opinions on naming.

**Comment by dmint789** [comment]
@jfly we've actually combined forces with the unofficial events stuff, and the naming is exactly the same as on our cubingcontests.com website, so you can just go ahead with the merge. We'll also likely be moving this project to the cubing organization in the near future.

**Review by lgarron — COMMENTED** [review]
These LGTM, although I'd still like a chance to review new icons in the future.

**Comment by jfly** [comment]
> I'd still like a chance to review new icons in the future

Let's have a separate conversation about that someday? I'm not immediately thrilled about that: I personally have never worked on project that requires more than 1 person (besides the contributor) to approve every change.

**Comment by dmint789** [comment]
I agree, I feel like requiring multiple reviews for such a small project is too much. Maybe we could just give 24 hours for people to leave their thoughts in the future.

**Pull request merged**
