### PR TITLE
Added icons for redi cube and master pyraminx.

### PR DESCRIPTION
**Pull request by MikeHughey1**
I added these two new icons for the Speedsolving.com weekly competition this year.

When considering this pull request, in addition to the icons themselves, please also consider whether the names of the icons are good enough.

### CODE REVIEW

**Comment by keemy** [comment]
for redi cube i think the name is good only minor thing to fix on icon would just be to change the sticker size to match that of the 3x3 stick size

**Comment by MikeHughey1** [comment]
Oh, it is a bit bigger than the 3x3x3 size, isn't it?  Sorry I didn't think
of that when I first did it, and I didn't really notice.  But now that you
mention it, it is noticeable.

Okay, I can do that; it might be a day or two before I get to it.

**Comment by keemy** [comment]
Hmm good question. I guess my thinking was something like this.

If I was going to make a redi cube icon I would probably take the 333 delete the middle sticker and attach 4 triangles to the 4 edges. 

Comparing to the other unusual puzzles is an interesting point but I guess the reason there is smaller white space for those is because they have smaller stickers and was trying to avoid having said stickers become too small such that they would look bad at the small size. Redi cube doesn't have this problem was what I was thinking if that makes sense.

I think that the inner sticker white space is probably not the hugest deal (the margin white space being semi consistent is more important). If you feel it looks better with the larger stickers maybe we can consider it that way?

**Comment by MikeHughey1** [comment]
I guess my problem here is that I'm noncommittal.  I could go either way.
It's not like it's that hard to change, and now that you've mentioned it,
the redi icon does look a bit big and blocky compared to 3x3x3.

So I'm really totally fine with changing it if you think it would look
better.  I kind of see your point that it might.

**Comment by MikeHughey1** [comment]
I made the changes, and I think I really like the change.  Everyone okay with this version?

**Comment by jfly** [comment]
This may only be noticeable at large sizes, but I don't think the `mpyram` is quite a triangle. Here's what I see if I rotate it about its center:

2019-01-04_07-58-09_dalinar

**Comment by MikeHughey1** [comment]
Ugh, yeah that's an artifact of my using integers for all the coordinates.  (I think you mean you don't think it's an *equilateral* triangle.) :-)

I can fix that; it's just a bit of work to do.

**Comment by jfly** [comment]
Looks much better!

2019-01-05_09-51-45_dalinar


@FatBoyXPC, can you take a look and merge this up if you're happy with it?

**Comment by FatBoyXPC** [comment]
I was happy w/these before all the revisions :joy:

**Pull request merged**
